version: '3.8'
services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
      args:
        MODE: example
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./web/:/usr/src/app/
